// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2011, 2012 IBM Corporation and others.
 *
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 *  The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 *  and the Eclipse Distribution License is available at
 *  http://www.eclipse.org/org/documents/edl-v10.php.
 *  
 *  Contributors:
 *  
 *	   Sam Padgett	       - initial API and implementation
 *     Michael Fiedler     - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *     Matthieu Helleboid   - Support for multiple Service Providers.
 *     Anass Radouani       - Support for multiple Service Providers.
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package com.sample.testing;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.ServletContextEvent;
import java.util.List;

import org.eclipse.lyo.oslc4j.core.model.ServiceProvider;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import com.sample.testing.servlet.ServiceProviderCatalogSingleton;
import com.sample.testing.ServiceProvider1Info;
import com.sample.testing.ServiceProvider2Info;
import com.sample.testing.resources.Requirement;
import com.sample.testing.resources.TestScript;


// Start of user code imports
import java.util.concurrent.ThreadLocalRandom;
import java.net.URI;
import java.net.URISyntaxException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.eclipse.lyo.oslc4j.core.model.Link;
import java.util.ArrayList;

import com.sample.testing.clients.RequirementsAdaptorClient;
// End of user code

// Start of user code pre_class_code
// End of user code

public class TestingToolManager {

    // Start of user code class_attributes
	private static final Logger log = LoggerFactory.getLogger(TestingToolManager.class);
    // End of user code
    
    
    // Start of user code class_methods
	private static int randomNumber(int origin, int bound) {
		return ThreadLocalRandom.current().nextInt(origin, bound);
	}

	private static Link queryForRandomRequirementLink() throws URISyntaxException {
//		try {
//			String[] requirements = RequirementsAdaptorClient.queryRequirements();
//			int index = randomNumber(0, requirements.length);
//			return new Link (new URI (requirements[index]));
//		} catch (Exception e) {
//            log.error("Failed to query resources", e);
            return null;
//		}
	}

	private static TestScript createRandomTestScript(String serviceProviderId, String id) {
		TestScript r = null;
		try {
			r = TestingToolResourcesFactory.createTestScript(serviceProviderId, id);
			r.setTitle("A sample TestScript with id:" + id);
			r.setDescription("A sample TestScript with id:" + id);
			r.setValidatesRequirement(queryForRandomRequirementLink());
		} catch (URISyntaxException e) {
            log.error("Failed to create resource", e);
		}
		return r;
	}

	private static List<TestScript> createRandomTestScripts(String serviceProviderId, int min, int max, int minId, int maxId)
    {
		int size = randomNumber(min, max);
		List<TestScript> resources = new ArrayList<TestScript>(size);
		for (int i = 0; i < size; i++) {
	    	resources.add(createRandomTestScript(serviceProviderId, Integer.toString(randomNumber(minId, maxId))));
		}
        return resources;
    }
    // End of user code

    public static void contextInitializeServletListener(final ServletContextEvent servletContextEvent)
    {
        
        // Start of user code contextInitializeServletListener
        // TODO Implement code to establish connection to data backbone etc ...
        // End of user code
    }

    public static void contextDestroyServletListener(ServletContextEvent servletContextEvent) 
    {
        
        // Start of user code contextDestroyed
        // TODO Implement code to shutdown connections to data backbone etc...
        // End of user code
    }

    public static ServiceProvider1Info[] getServiceProvider1Infos(HttpServletRequest httpServletRequest)
    {
        ServiceProvider1Info[] serviceProviderInfos = {};
        
        // Start of user code "ServiceProvider1Info[] getServiceProvider1Infos(...)"
        // TODO Implement code to return the set of ServiceProviders
        // End of user code
        return serviceProviderInfos;
    }
    public static ServiceProvider2Info[] getServiceProvider2Infos(HttpServletRequest httpServletRequest)
    {
        ServiceProvider2Info[] serviceProviderInfos = {};
        
        // Start of user code "ServiceProvider2Info[] getServiceProvider2Infos(...)"
        // TODO Implement code to return the set of ServiceProviders
        // End of user code
        return serviceProviderInfos;
    }

    public static List<TestScript> queryTestScripts(HttpServletRequest httpServletRequest, final String serviceProviderId, String where, int page, int limit)
    {
        List<TestScript> resources = null;
        
        // Start of user code queryTestScripts
        resources = createRandomTestScripts(serviceProviderId, 0, 50, 1, 5000);
        // End of user code
        return resources;
    }
    public static TestScript createTestScriptForCreationFactory(HttpServletRequest httpServletRequest, final TestScript aResource, final String serviceProviderId)
    {
        TestScript newResource = null;
        
        // Start of user code createTestScriptForCreationFactory
        // TODO Implement code to create a resource
        // End of user code
        return newResource;
    }


    public static TestScript getTestScript(HttpServletRequest httpServletRequest, final String serviceProviderId, final String testScriptId)
    {
        TestScript aResource = null;
        
        // Start of user code getTestScript
        aResource = createRandomTestScript(serviceProviderId, testScriptId);
        // End of user code
        return aResource;
    }



    public static List<Requirement> queryRequirementsForQueryCapability1(HttpServletRequest httpServletRequest, final String serviceProviderId, String where, int page, int limit)
    {
        List<Requirement> resources = null;
        
        // Start of user code queryRequirementsForQueryCapability1
        // TODO Implement code to return a set of resources
        // End of user code
        return resources;
    }
    public static TestScript createTestScriptForCreationFactory1(HttpServletRequest httpServletRequest, final TestScript aResource, final String serviceProviderId)
    {
        TestScript newResource = null;
        
        // Start of user code createTestScriptForCreationFactory1
        // TODO Implement code to create a resource
        // End of user code
        return newResource;
    }


    public static Requirement getRequirement(HttpServletRequest httpServletRequest, final String serviceProviderId, final String requirementId)
    {
        Requirement aResource = null;
        
        // Start of user code getRequirement
        // TODO Implement code to return a resource
        // End of user code
        return aResource;
    }



    public static List<Requirement> queryRequirementsForQueryCapability2(HttpServletRequest httpServletRequest, final String serviceProviderId, String where, int page, int limit)
    {
        List<Requirement> resources = null;
        
        // Start of user code queryRequirementsForQueryCapability2
        // TODO Implement code to return a set of resources
        // End of user code
        return resources;
    }




    public static String getETagFromRequirement(final Requirement aResource)
    {
        String eTag = null;
        // Start of user code getETagFromRequirement
        // TODO Implement code to return an ETag for a particular resource
        // End of user code
        return eTag;
    }
    public static String getETagFromTestScript(final TestScript aResource)
    {
        String eTag = null;
        // Start of user code getETagFromTestScript
        // TODO Implement code to return an ETag for a particular resource
        // End of user code
        return eTag;
    }

}
